export default {
  LOGIN: '/auth/login',
  REGISTER: '/account/users',
  USER_INFO: '/account/users/info',
  MAP: '/map/map-points',
  MAP_POINT_TYPES: '/map/map-point-types',
  UNREAD_NOTIFICATIONS: '/notification/unread-notifications',
  NOTIFICATIONS: '/notification/notifications',
  CARS: '/car/cars',
  EXAMINATIONS: '/examination/examinations',
  LAST_EXAMINATION: '/examination/examinations/last-examination',
  EXAMINATION_DOCUMENTS: '/examination/documents',
  INSURANCES: '/insurance/insurances',
  LAST_THIRD_PARTY_INSURANCE: '/insurance/insurances/last-third-party-insurance',
  LAST_FULLY_INSURANCE: '/insurance/insurances/last-fully-insurance',
  INSURANCE_DOCUMENTS: '/insurance/documents',
  SERVICES: '/car/services',
  REPORTS: '/car/reports',
};
